[package]
name = "agentsassemble-domain"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
ts-rs.workspace = true
unicode-general-category.workspace = true
uuid.workspace = true

[lints]
workspace = true
