use agentsassemble_domain::{AgentSession, CURRENT_RUNTIME_PROFILE_VERSION, DurableAgentSession};
use chrono::{DateTime, Utc};

pub(crate) fn durable_session(
    room_id: &str,
    session_id: &str,
    display_name: &str,
    provider_kind: &str,
    model: &str,
    transport: &str,
) -> DurableAgentSession {
    let now = DateTime::parse_from_rfc3339("2026-08-23T00:00:00Z")
        .unwrap_or_else(|error| panic!("parse fixture timestamp: {error}"))
        .with_timezone(&Utc);
    DurableAgentSession {
        public: AgentSession {
            room_id: room_id.to_owned(),
            session_id: session_id.to_owned(),
            participant_id: session_id.to_owned(),
            display_name: display_name.to_owned(),
            status: "available".to_owned(),
            runtime_status: "starting".to_owned(),
            enabled: true,
            provider_kind: provider_kind.to_owned(),
            runtime_kind: "live_cli".to_owned(),
            connection_kind: "native_cli_bridge".to_owned(),
            external_owned: false,
            process_ownership: "server".to_owned(),
            model: model.to_owned(),
            reasoning_effort: "high".to_owned(),
            service_tier: String::new(),
            variant: String::new(),
            execution_harness: "builtin".to_owned(),
            permission_mode: "meeting_read_only".to_owned(),
            max_output_tokens: 0,
            catalog_revision: "revision".to_owned(),
            transport: transport.to_owned(),
            last_seen_event_id: String::new(),
            last_seen_seq: 0,
            last_provider_sync_event_id: String::new(),
            last_provider_sync_seq: 0,
            bootstrap_cutoff_seq: 0,
            turn_count: 0,
            active_turn_id: String::new(),
            turn_phase: String::new(),
            last_error: String::new(),
            last_error_code: String::new(),
            recovery_required: false,
            provider_session_active: false,
            provider_session_reused: false,
            created_at: now,
            updated_at: now,
        },
        executable: String::new(),
        executable_identity: String::new(),
        workspace: String::new(),
        workspace_identity: String::new(),
        runtime_profile_key: "profile".to_owned(),
        runtime_profile_version: CURRENT_RUNTIME_PROFILE_VERSION,
        provider_session_id: String::new(),
        runtime_handle_id: String::new(),
        runtime_owner_id: String::new(),
        runtime_lease_token: String::new(),
        pending_inputs: Vec::new(),
        inflight_inputs: Vec::new(),
        active_source_event_id: String::new(),
        input_up_to_event_id: String::new(),
        input_up_to_seq: 0,
        lifecycle_intent_action: String::new(),
        lifecycle_intent_id: String::new(),
        lifecycle_intent_status: String::new(),
    }
}
