// Generated by scripts/generate_room_event_types.py. Do not edit.
import type { RoomAgentSession } from "../api/agentSessions";

export interface PublicProviderRequestOption {
  id: string;
  label: string;
  kind: string;
  description: string;
}

export interface PublicProviderRequestQuestion {
  id: string;
  header: string;
  question: string;
  options: PublicProviderRequestOption[];
  multiple: boolean;
  is_other: boolean;
  is_secret: boolean;
}

export interface PublicProviderRequest {
  provider_request_id?: string;
  participant_id?: string;
  display_name?: string;
  provider_kind?: string;
  request_kind?: string;
  response_kind?: string;
  title?: string;
  description?: string;
  status?: string;
  options?: PublicProviderRequestOption[];
  questions?: PublicProviderRequestQuestion[];
  timeout_seconds?: number;
  action_url?: string;
}

export interface PublicRoomActor {
  participant_id?: string;
  participant_type?: string;
}

export interface PublicRoomAttachment {
  id: string;
  filename: string;
  content_type: string;
  size: number;
  is_image: boolean;
  url: string;
  download_url: string;
}

export interface PublicRoomGlobalAppearance {
  banner_preset: string;
  banner_image_url: string;
  icon_image_url: string;
  icon_label: string;
  invite_scope: string;
}

export interface PublicRoomGlobalChannel {
  id: string;
  name: string;
  type: string;
  position: number;
  created_at: string;
}

export interface PublicRoomGlobalSettings {
  settings_revision: string;
  label: string;
  topic: string;
  appearance: PublicRoomGlobalAppearance;
  conversation_mode: string;
  tool_mode: string;
  ordered_exclude_previous_speaker: boolean;
  max_relay_turns: number;
  channels: PublicRoomGlobalChannel[];
  activity_plugin?: string;
}

export interface RoomEvent {
  v: number;
  id: string;
  seq: number;
  created_at: string;
  room_id: string;
  type: string;
  actor: PublicRoomActor;
  participant_id?: string;
  participant_type?: string;
  actor_id?: string;
  actor_type?: string;
  owner_id?: string;
  session_id?: string;
  turn_id?: string;
  source_event_id?: string;
  display_name?: string;
  avatar_image_url?: string;
  provider_kind?: string;
  role?: string;
  content?: string;
  target_event_id?: string;
  target_seq?: number;
  edited_at?: string;
  deleted_at?: string;
  message_deleted?: boolean;
  message_kind?: string;
  target_agent_id?: string;
  vote_id?: string;
  vote_question?: string;
  vote_options?: string[];
  vote_duration_seconds?: number;
  vote_deadline_at?: string;
  vote_choice?: string;
  visibility?: string;
  phase?: string;
  status?: string;
  activity_kind?: string;
  category?: string;
  activity_id?: string;
  activity_title?: string;
  activity_detail?: string;
  attachments?: PublicRoomAttachment[];
  latency?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  diagnostics?: Record<string, unknown>;
  agent_session?: RoomAgentSession;
  message_source?: string;
  relay_depth?: number;
  reason_code?: string;
  room_settings?: PublicRoomGlobalSettings;
  provider_request?: PublicProviderRequest;
  plugin_id?: string;
  plugin_payload?: Record<string, unknown>;
  plugin_code?: string;
}
