import type { RoomAgentSession } from "../api";

export function agentSessionFixture(
  overrides: Partial<RoomAgentSession> = {},
): RoomAgentSession {
  return {
    room_id: "room-test",
    session_id: "session-test",
    participant_id: "agent-test",
    display_name: "Agent Test",
    status: "stopped",
    runtime_status: "stopped",
    enabled: false,
    provider_kind: "codex_live_session",
    runtime_kind: "live_cli",
    connection_kind: "native_cli_bridge",
    external_owned: false,
    process_ownership: "server",
    model: "",
    reasoning_effort: "",
    service_tier: "",
    variant: "",
    execution_harness: "builtin",
    permission_mode: "meeting_read_only",
    max_output_tokens: 0,
    catalog_revision: "catalog-test",
    persona_card_id: "",
    persona_card: null,
    transport: "stdio_jsonl",
    last_seen_event_id: "",
    last_seen_seq: 0,
    last_provider_sync_event_id: "",
    last_provider_sync_seq: 0,
    bootstrap_cutoff_seq: 0,
    turn_count: 0,
    active_turn_id: "",
    turn_phase: "",
    last_error: "",
    last_error_code: "",
    recovery_required: false,
    provider_session_active: false,
    provider_session_reused: false,
    created_at: "2026-08-25T00:00:00Z",
    updated_at: "2026-08-25T00:00:00Z",
    ...overrides,
  };
}
