CREATE TABLE IF NOT EXISTS human_room_sessions (admission_key BLOB PRIMARY KEY CHECK(typeof(admission_key) = 'blob' AND length(admission_key) = 32),
    key_kind TEXT NOT NULL CHECK(key_kind IN ('one_use',
    'reusable',
    'recovery')),
    first_request_id TEXT CHECK(length(first_request_id) = 36),
    invite_id TEXT,
    payload_hash BLOB CHECK(payload_hash IS NULL OR (typeof(payload_hash) = 'blob' AND length(payload_hash) = 32)),
    session_fingerprint BLOB NOT NULL UNIQUE CHECK(typeof(session_fingerprint) = 'blob' AND length(session_fingerprint) = 32),
    room_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    participant_id TEXT NOT NULL,
    client_kind TEXT NOT NULL CHECK(client_kind = 'browser'),
    invite_scope TEXT NOT NULL CHECK(invite_scope IN ('read_write',
    'read_only')),
    browser_credential_fingerprint BLOB NOT NULL CHECK(typeof(browser_credential_fingerprint) = 'blob' AND length(browser_credential_fingerprint) = 32),
    reusable_identity_fingerprint BLOB CHECK(reusable_identity_fingerprint IS NULL OR (typeof(reusable_identity_fingerprint) = 'blob' AND length(reusable_identity_fingerprint) = 32)),
    result_json TEXT NOT NULL,
    admitted_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    state TEXT NOT NULL CHECK(state IN ('active',
    'ended')),
    CHECK(expires_at > admitted_at),
    CHECK((key_kind = 'recovery' AND invite_id IS NULL AND first_request_id IS NULL AND payload_hash IS NULL) OR (key_kind IN ('one_use',
    'reusable') AND invite_id IS NOT NULL AND first_request_id IS NOT NULL AND payload_hash IS NOT NULL)),
    CHECK((key_kind = 'one_use' AND reusable_identity_fingerprint IS NULL) OR (key_kind IN ('reusable',
    'recovery') AND reusable_identity_fingerprint IS NOT NULL AND length(reusable_identity_fingerprint) = 32 AND reusable_identity_fingerprint = browser_credential_fingerprint)),
    FOREIGN KEY(invite_id,
    room_id,
    invite_scope,
    key_kind) REFERENCES room_invites(invite_id,
    room_id,
    invite_scope,
    key_kind) ON DELETE CASCADE,
    FOREIGN KEY(room_id) REFERENCES rooms(room_id) ON DELETE CASCADE,
    FOREIGN KEY(user_id,
    participant_id) REFERENCES user_profiles(user_id,
    participant_id) ON DELETE CASCADE,
    FOREIGN KEY(reusable_identity_fingerprint,
    user_id) REFERENCES human_device_credentials(credential_fingerprint,
    user_id),
    FOREIGN KEY(room_id,
    participant_id) REFERENCES participants(room_id,
    participant_id) ON DELETE CASCADE);
